import { useCallback } from 'react'
import { useSceneSyncCoordinator } from './useSceneSyncCoordinator.js'

export function useAppSyncCoordinatorState({
    liveSyncFeatureEnabled,
    shouldSyncServerScene,
    captureSavedViewFromControls,
    controlsRef,
    sceneSettings,
    objects,
    renderSettings,
    setRenderSettings,
    presentation,
    setPresentation,
    isGridVisible,
    setIsGridVisible,
    isGizmoVisible,
    setIsGizmoVisible,
    isPerfVisible,
    setIsPerfVisible,
    remoteSceneVersion,
    sceneVersion,
    remoteAssetsRef,
    remoteAssetsBaseRef,
    remoteAssetsManifest,
    remoteAssetsBaseUrl,
    persistSceneDataWithStatus,
    updateSceneSignature,
    submitSceneOps,
    spaceId,
    liveClientIdRef,
    sceneVersionRef,
    setSceneVersion,
    fileInputRef,
    setRemoteSceneVersion,
    resetRemoteAssets,
    getAssetBlob,
    getAssetSourceUrl,
    resetAssetStoreQuotaState,
    restoreAssetsFromPayload,
    setRemoteAssetsManifest,
    setObjects,
    clearSelection,
    defaultGridAppearance,
    defaultRenderSettings,
    isLoading,
    canPublishToServer,
    canUploadServerAssets,
    isOfflineMode,
    setOfflineMode,
    serverAssetBaseUrl,
    markServerSync,
    applyRemoteScene,
    getServerScene,
    uploadAssetToServer,
    setServerAssetSyncProgress
} = {}) {
    const coordinator = useSceneSyncCoordinator({
        controlsRef,
        cameraPosition: sceneSettings.cameraPosition,
        cameraTarget: sceneSettings.cameraTarget,
        setCameraPosition: sceneSettings.setCameraPosition,
        setCameraTarget: sceneSettings.setCameraTarget,
        captureSavedViewFromControls,
        objects,
        backgroundColor: sceneSettings.backgroundColor,
        gridSize: sceneSettings.gridSize,
        gridAppearance: sceneSettings.gridAppearance,
        renderSettings,
        transformSnaps: sceneSettings.transformSnaps,
        presentation,
        isGridVisible,
        isGizmoVisible,
        isPerfVisible,
        directionalLight: sceneSettings.directionalLight,
        ambientLight: sceneSettings.ambientLight,
        default3DView: sceneSettings.default3DView,
        remoteSceneVersion,
        sceneVersion,
        remoteAssetsRef,
        remoteAssetsBaseRef,
        remoteAssetsManifest,
        remoteAssetsBaseUrl,
        persistSceneDataWithStatus,
        updateSceneSignature,
        shouldSyncServerScene: !liveSyncFeatureEnabled && shouldSyncServerScene,
        submitSceneOps,
        spaceId,
        liveClientIdRef,
        sceneVersionRef,
        setSceneVersion,
        fileInputRef,
        setRemoteSceneVersion,
        resetRemoteAssets,
        getAssetBlob,
        getAssetSourceUrl,
        resetAssetStoreQuotaState,
        restoreAssetsFromPayload,
        setRemoteAssetsManifest,
        setObjects,
        setBackgroundColor: sceneSettings.setBackgroundColor,
        setGridSize: sceneSettings.setGridSize,
        setGridAppearance: sceneSettings.setGridAppearance,
        setRenderSettings,
        setTransformSnaps: sceneSettings.setTransformSnaps,
        setIsGridVisible,
        setIsGizmoVisible,
        setIsPerfVisible,
        setPresentation,
        setAmbientLight: sceneSettings.setAmbientLight,
        setDirectionalLight: sceneSettings.setDirectionalLight,
        setDefault3DView: sceneSettings.setDefault3DView,
        clearSelection,
        defaultGridAppearance,
        defaultRenderSettings,
        isLoading,
        canPublishToServer,
        canUploadServerAssets,
        isOfflineMode,
        serverAssetBaseUrl,
        setOfflineMode,
        markServerSync,
        applyRemoteScene,
        getServerScene,
        uploadAssetToServer,
        setServerAssetSyncProgress
    })

    const handleToggleOfflineMode = useCallback(() => {
        setOfflineMode(!isOfflineMode)
        alert(
            !isOfflineMode
                ? 'Offline mode enabled: server sync disabled.'
                : 'Offline mode disabled: server sync available.'
        )
    }, [isOfflineMode, setOfflineMode])

    return {
        ...coordinator,
        handleToggleOfflineMode
    }
}

export default useAppSyncCoordinatorState
