import { renderHook } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { useAppContextValues } from './useAppContextValues.js'

function createProps(overrides = {}) {
    const noop = vi.fn()
    const sceneSettings = {
        backgroundColor: '#000000',
        setBackgroundColor: noop,
        gridSize: 10,
        setGridSize: noop,
        cameraSettings: { fov: 60 },
        setCameraSettings: noop,
        default3DView: 'perspective',
        ambientLight: 0.5,
        setAmbientLight: noop,
        directionalLight: 0.8,
        setDirectionalLight: noop,
        transformSnaps: { move: 1, rotate: 15, scale: 0.1 },
        setTransformSnaps: noop,
        gridAppearance: { opacity: 1 },
        setGridAppearance: noop,
        cameraPosition: [0, 1, 4],
        cameraTarget: [0, 0, 0]
    }

    return {
        sceneSettings,
        renderSettings: { toneMapping: 'aces' },
        setRenderSettings: noop,
        presentation: { mode: 'scene' },
        setPresentation: noop,
        presentationMode: 'scene',
        setPresentationMode: noop,
        presentationSourceType: 'html',
        setPresentationSourceType: noop,
        presentationUrl: '',
        setPresentationUrl: noop,
        presentationHtml: '<div>Hello</div>',
        setPresentationHtml: noop,
        presentationFixedCamera: null,
        setPresentationFixedCamera: noop,
        selectionGroups: [{ id: 'group-1' }],
        canUndo: true,
        canRedo: false,
        liveSyncFeatureEnabled: true,
        supportsServerSpaces: true,
        isLiveSyncEnabled: true,
        setIsLiveSyncEnabled: noop,
        canSyncServerScene: true,
        spaceId: 'main',
        isOfflineMode: false,
        setOfflineMode: noop,
        shouldSyncServerScene: true,
        canPublishToServer: true,
        isReadOnly: false,
        serverSyncInfo: { ts: 1, label: 'Synced with server' },
        localSaveStatus: { ts: 2, label: 'Saved locally' },
        uploadProgress: { active: false, completed: 0, total: 0 },
        assetRestoreProgress: { active: false, completed: 0, total: 0 },
        serverAssetSyncProgress: { active: false, completed: 0, total: 0, label: '' },
        serverAssetSyncPending: 0,
        mediaOptimizationStatus: { active: false, completed: 0, total: 0, label: '' },
        remoteAssetsManifest: [],
        remoteAssetsBaseUrl: '',
        setRemoteAssetsManifest: noop,
        isStatusPanelVisible: true,
        setIsStatusPanelVisible: noop,
        displayName: 'Tester',
        setDisplayName: noop,
        effectiveDisplayName: 'Tester',
        isSocketConnected: true,
        isSceneStreamConnected: true,
        sceneStreamState: 'connected',
        sceneStreamError: '',
        collaborators: [],
        usersInSpace: [],
        participantRoster: [],
        remoteCursorMarkers: [{ id: 'cursor-1' }],
        spaces: [{ id: 'main' }],
        newSpaceName: '',
        setNewSpaceName: noop,
        openAfterCreateTarget: 'editor',
        setOpenAfterCreateTarget: noop,
        spaceNameFeedback: '',
        canCreateSpace: true,
        tempSpaceTtlHours: 24,
        isCreatingSpace: false,
        guardEditAction: (fn) => fn,
        handleAddObject: noop,
        handleSaveView: noop,
        handleFrameAll: noop,
        handleFrameSelection: noop,
        handleUpdateTransformSnaps: noop,
        handleSave: noop,
        handleLoadClick: noop,
        handleKeepCurrentWorld: noop,
        handleClear: noop,
        handleAssetFilesUpload: noop,
        handleUndo: noop,
        handleRedo: noop,
        selectObject: noop,
        handleSelectObjectFromOutliner: noop,
        handleToggleObjectVisibility: noop,
        selectAllObjects: noop,
        resetAxisLock: noop,
        toggleAdminMode: noop,
        handleManualMediaOptimization: noop,
        handleBatchMediaOptimization: noop,
        copySelectedObject: noop,
        pasteClipboardObject: noop,
        cutSelectedObject: noop,
        duplicateSelectedObject: noop,
        deleteSelectedObject: noop,
        handleUngroupSelection: noop,
        expandIdsWithGroups: noop,
        handleCreateSelectionGroup: noop,
        handleSelectSelectionGroup: noop,
        handleDeleteSelectionGroup: noop,
        handleCreateNamedSpace: noop,
        handleOpenSpace: noop,
        handleCopySpaceLink: noop,
        handleDeleteSpace: noop,
        handleRenameSpace: noop,
        handleToggleSpacePermanent: noop,
        handleToggleSpaceEditLock: noop,
        handleReloadFromServer: noop,
        handlePublishToServer: noop,
        socketEmit: noop,
        controlsRef: { current: null },
        fileInputRef: { current: null },
        handleFileLoad: noop,
        sceneButtons: [{ key: 'save' }],
        panelButtons: [{ key: 'view' }],
        adminButtons: [{ key: 'admin' }],
        displayButtons: [{ key: 'display' }],
        xrButtons: [{ key: 'xr' }],
        hiddenUiButtons: [{ key: 'toggle-ui' }],
        isLoading: false,
        isFileDragActive: false,
        mediaOptimizationPreference: 'balanced',
        setMediaOptimizationPreference: noop,
        canCreateGroupSelection: true,
        xrStore: { isPresenting: false },
        currentCameraSettings: { fov: 60 },
        cameraPosition: [0, 1, 4],
        rendererRef: { current: null },
        handleCanvasPointerMove: noop,
        handleCanvasPointerLeave: noop,
        ...overrides
    }
}

describe('useAppContextValues', () => {
    it('keeps server capability in sync context and preserves grouped layout props', () => {
        const props = createProps()
        const { result } = renderHook(() => useAppContextValues(props))

        expect(result.current.syncState.supportsServerSpaces).toBe(true)
        expect(result.current.syncState.spaceId).toBe('main')
        expect(result.current.editorLayoutProps.controlButtons.sceneButtons).toBe(props.sceneButtons)
        expect(result.current.editorLayoutProps.controlButtons.xrButtons).toBe(props.xrButtons)
        expect(result.current.handlers.handleAddObject).toBe(props.handleAddObject)
        expect(result.current.refs.controlsRef).toBe(props.controlsRef)
    })
})
