import { useEffect } from 'react'
import { useCollaborativeSession } from './useCollaborativeSession.js'
import { useSceneApply } from './useSceneApply.js'
import { useSceneInitializer } from './useSceneInitializer.js'

export function useAppSyncSessionState({
    liveSyncFeatureEnabled,
    sceneStorageKey,
    spaceId,
    canAccessServerSpaces,
    isOfflineMode,
    isLiveSyncEnabled,
    isPointerDragging,
    buildSpaceApiUrl,
    serverAssetBaseUrl,
    supportsServerSpaces,
    getServerScene,
    getServerSceneOps,
    submitSceneOps,
    sceneSettings,
    objects,
    renderSettings,
    setRenderSettings,
    presentation,
    setPresentation,
    sceneVersion,
    setSceneVersion,
    sceneVersionRef,
    setRemoteSceneVersion,
    skipServerLoadRef,
    persistSceneDataWithStatus,
    markServerSync,
    setAssetRestoreProgress,
    setRemoteAssetsManifest,
    resetRemoteAssets,
    resetAssetStoreQuotaState,
    restoreAssetsFromPayload,
    clearSelection,
    getAssetUrlCandidates,
    getAssetSourceUrl,
    defaultGridAppearance,
    defaultRenderSettings,
    defaultSceneRemoteBase,
    legacySceneRemoteBase,
    setObjects,
    setIsGridVisible,
    setIsGizmoVisible,
    setIsPerfVisible
} = {}) {
    useEffect(() => {
        sceneVersionRef.current = sceneVersion
    }, [sceneVersion, sceneVersionRef])

    const { updateSceneSignature, applyRemoteScene, applyScenePatch } = useSceneApply({
        persistSceneDataWithStatus,
        resetAssetStoreQuotaState,
        restoreAssetsFromPayload,
        setAssetRestoreProgress,
        setRemoteAssetsManifest,
        setSceneVersion,
        setObjects,
        setBackgroundColor: sceneSettings.setBackgroundColor,
        setGridSize: sceneSettings.setGridSize,
        setGridAppearance: sceneSettings.setGridAppearance,
        setRenderSettings,
        setTransformSnaps: sceneSettings.setTransformSnaps,
        setIsGridVisible,
        setIsGizmoVisible,
        setIsPerfVisible,
        setPresentation,
        setAmbientLight: sceneSettings.setAmbientLight,
        setDirectionalLight: sceneSettings.setDirectionalLight,
        setCameraPosition: sceneSettings.setCameraPosition,
        setCameraTarget: sceneSettings.setCameraTarget,
        clearSelection,
        setRemoteSceneVersion,
        defaultGridAppearance,
        defaultRenderSettings,
        defaultSceneRemoteBase,
        legacySceneRemoteBase,
        getAssetUrlCandidates,
        getAssetSourceUrl
    })

    const { isLoading } = useSceneInitializer({
        sceneStorageKey,
        spaceId,
        canPublishToServer: canAccessServerSpaces,
        isOfflineMode,
        preferServerScene: liveSyncFeatureEnabled && canAccessServerSpaces,
        forceServerAssetsBase: canAccessServerSpaces,
        skipServerLoadRef,
        serverAssetBaseUrl,
        applyRemoteScene,
        markServerSync,
        resetRemoteAssets,
        setRemoteSceneVersion,
        setRemoteAssetsManifest,
        persistSceneDataWithStatus,
        updateSceneSignature,
        setObjects,
        setBackgroundColor: sceneSettings.setBackgroundColor,
        setGridSize: sceneSettings.setGridSize,
        setGridAppearance: sceneSettings.setGridAppearance,
        setRenderSettings,
        setTransformSnaps: sceneSettings.setTransformSnaps,
        setIsGridVisible,
        setIsGizmoVisible,
        setIsPerfVisible,
        setPresentation,
        setAmbientLight: sceneSettings.setAmbientLight,
        setDirectionalLight: sceneSettings.setDirectionalLight,
        setDefault3DView: sceneSettings.setDefault3DView,
        setCameraPosition: sceneSettings.setCameraPosition,
        setCameraTarget: sceneSettings.setCameraTarget,
        setSceneVersion,
        getServerScene,
        defaultGridAppearance,
        defaultRenderSettings,
        defaultSceneRemoteBase
    })

    const session = useCollaborativeSession({
        enabled: liveSyncFeatureEnabled,
        isLoading,
        canAccessServerSpaces,
        isOfflineMode,
        isLiveSyncEnabled,
        isPointerDragging,
        spaceId,
        supportsServerSpaces,
        buildSpaceApiUrl,
        serverAssetBaseUrl,
        getServerScene,
        getServerSceneOps: supportsServerSpaces ? getServerSceneOps : null,
        submitSceneOps,
        objects,
        backgroundColor: sceneSettings.backgroundColor,
        gridSize: sceneSettings.gridSize,
        gridAppearance: sceneSettings.gridAppearance,
        renderSettings,
        ambientLight: sceneSettings.ambientLight,
        directionalLight: sceneSettings.directionalLight,
        transformSnaps: sceneSettings.transformSnaps,
        presentation,
        default3DView: sceneSettings.default3DView,
        applyRemoteScene,
        applyScenePatch,
        setSceneVersion,
        sceneVersionRef,
        setObjects,
        setBackgroundColor: sceneSettings.setBackgroundColor,
        setGridSize: sceneSettings.setGridSize,
        setGridAppearance: sceneSettings.setGridAppearance,
        setRenderSettings,
        setTransformSnaps: sceneSettings.setTransformSnaps,
        setPresentation,
        setAmbientLight: sceneSettings.setAmbientLight,
        setDirectionalLight: sceneSettings.setDirectionalLight,
        setDefault3DView: sceneSettings.setDefault3DView,
        defaultGridAppearance
    })

    return {
        updateSceneSignature,
        applyRemoteScene,
        isLoading,
        ...session
    }
}

export default useAppSyncSessionState
