import { useMemo } from 'react'

export function useAppContextValues({
    sceneSettings,
    renderSettings,
    setRenderSettings,
    presentation,
    setPresentation,
    presentationMode,
    setPresentationMode,
    presentationSourceType,
    setPresentationSourceType,
    presentationUrl,
    setPresentationUrl,
    presentationHtml,
    setPresentationHtml,
    presentationFixedCamera,
    setPresentationFixedCamera,
    selectionGroups,
    canUndo,
    canRedo,
    liveSyncFeatureEnabled,
    supportsServerSpaces,
    isLiveSyncEnabled,
    setIsLiveSyncEnabled,
    canSyncServerScene,
    spaceId,
    isOfflineMode,
    setOfflineMode,
    shouldSyncServerScene,
    canPublishToServer,
    isReadOnly,
    serverSyncInfo,
    localSaveStatus,
    uploadProgress,
    assetRestoreProgress,
    serverAssetSyncProgress,
    serverAssetSyncPending,
    mediaOptimizationStatus,
    remoteAssetsManifest,
    remoteAssetsBaseUrl,
    setRemoteAssetsManifest,
    isStatusPanelVisible,
    setIsStatusPanelVisible,
    displayName,
    setDisplayName,
    effectiveDisplayName,
    isSocketConnected,
    isSceneStreamConnected,
    sceneStreamState,
    sceneStreamError,
    collaborators,
    usersInSpace,
    participantRoster,
    remoteCursorMarkers,
    spaces,
    newSpaceName,
    setNewSpaceName,
    openAfterCreateTarget,
    setOpenAfterCreateTarget,
    spaceNameFeedback,
    canCreateSpace,
    tempSpaceTtlHours,
    isCreatingSpace,
    guardEditAction,
    handleAddObject,
    handleSaveView,
    handleFrameAll,
    handleFrameSelection,
    handleUpdateTransformSnaps,
    handleSave,
    handleLoadClick,
    handleKeepCurrentWorld,
    handleClear,
    handleAssetFilesUpload,
    handleUndo,
    handleRedo,
    selectObject,
    handleSelectObjectFromOutliner,
    handleToggleObjectVisibility,
    selectAllObjects,
    resetAxisLock,
    toggleAdminMode,
    handleManualMediaOptimization,
    handleBatchMediaOptimization,
    copySelectedObject,
    pasteClipboardObject,
    cutSelectedObject,
    duplicateSelectedObject,
    deleteSelectedObject,
    handleUngroupSelection,
    expandIdsWithGroups,
    handleCreateSelectionGroup,
    handleSelectSelectionGroup,
    handleDeleteSelectionGroup,
    handleCreateNamedSpace,
    handleOpenSpace,
    handleCopySpaceLink,
    handleDeleteSpace,
    handleRenameSpace,
    handleToggleSpacePermanent,
    handleToggleSpaceEditLock,
    handleReloadFromServer,
    handlePublishToServer,
    socketEmit,
    controlsRef,
    fileInputRef,
    handleFileLoad,
    sceneButtons,
    panelButtons,
    adminButtons,
    displayButtons,
    xrButtons,
    hiddenUiButtons,
    isLoading,
    isFileDragActive,
    mediaOptimizationPreference,
    setMediaOptimizationPreference,
    canCreateGroupSelection,
    xrStore,
    currentCameraSettings,
    cameraPosition,
    rendererRef,
    handleCanvasPointerMove,
    handleCanvasPointerLeave
} = {}) {
    const sceneSettingsContext = useMemo(
        () => ({
            backgroundColor: sceneSettings.backgroundColor,
            setBackgroundColor: sceneSettings.setBackgroundColor,
            gridSize: sceneSettings.gridSize,
            setGridSize: sceneSettings.setGridSize,
            cameraSettings: sceneSettings.cameraSettings,
            setCameraSettings: sceneSettings.setCameraSettings,
            default3DView: sceneSettings.default3DView,
            ambientLight: sceneSettings.ambientLight,
            setAmbientLight: sceneSettings.setAmbientLight,
            directionalLight: sceneSettings.directionalLight,
            setDirectionalLight: sceneSettings.setDirectionalLight,
            transformSnaps: sceneSettings.transformSnaps,
            setTransformSnaps: sceneSettings.setTransformSnaps,
            gridAppearance: sceneSettings.gridAppearance,
            setGridAppearance: sceneSettings.setGridAppearance,
            renderSettings,
            setRenderSettings,
            presentation,
            setPresentation,
            presentationMode,
            setPresentationMode,
            presentationSourceType,
            setPresentationSourceType,
            presentationUrl,
            setPresentationUrl,
            presentationHtml,
            setPresentationHtml,
            presentationFixedCamera,
            setPresentationFixedCamera,
            cameraPosition: sceneSettings.cameraPosition,
            cameraTarget: sceneSettings.cameraTarget,
            selectionGroups,
            canUndo,
            canRedo
        }),
        [
            sceneSettings,
            renderSettings,
            setRenderSettings,
            presentation,
            setPresentation,
            presentationMode,
            setPresentationMode,
            presentationSourceType,
            setPresentationSourceType,
            presentationUrl,
            setPresentationUrl,
            presentationHtml,
            setPresentationHtml,
            presentationFixedCamera,
            setPresentationFixedCamera,
            selectionGroups,
            canUndo,
            canRedo
        ]
    )

    const syncState = useMemo(
        () => ({
            liveSyncFeatureEnabled: Boolean(liveSyncFeatureEnabled),
            supportsServerSpaces,
            isLiveSyncEnabled,
            setIsLiveSyncEnabled,
            canSyncServerScene,
            spaceId,
            isOfflineMode,
            setOfflineMode,
            shouldSyncServerScene,
            canPublishToServer,
            isReadOnly,
            serverSyncInfo,
            localSaveStatus,
            uploadProgress,
            assetRestoreProgress,
            serverAssetSyncProgress,
            serverAssetSyncPending,
            mediaOptimizationStatus,
            remoteAssetsManifest,
            remoteAssetsBaseUrl,
            setRemoteAssetsManifest,
            isStatusPanelVisible,
            setIsStatusPanelVisible,
            displayName,
            setDisplayName,
            effectiveDisplayName,
            isSocketConnected,
            isSceneStreamConnected,
            sceneStreamState,
            sceneStreamError,
            collaborators,
            usersInSpace,
            participantRoster,
            remoteCursorMarkers
        }),
        [
            liveSyncFeatureEnabled,
            supportsServerSpaces,
            isLiveSyncEnabled,
            setIsLiveSyncEnabled,
            canSyncServerScene,
            spaceId,
            isOfflineMode,
            setOfflineMode,
            shouldSyncServerScene,
            canPublishToServer,
            isReadOnly,
            serverSyncInfo,
            localSaveStatus,
            uploadProgress,
            assetRestoreProgress,
            serverAssetSyncProgress,
            serverAssetSyncPending,
            mediaOptimizationStatus,
            remoteAssetsManifest,
            remoteAssetsBaseUrl,
            setRemoteAssetsManifest,
            isStatusPanelVisible,
            setIsStatusPanelVisible,
            displayName,
            setDisplayName,
            effectiveDisplayName,
            isSocketConnected,
            isSceneStreamConnected,
            sceneStreamState,
            sceneStreamError,
            collaborators,
            usersInSpace,
            participantRoster,
            remoteCursorMarkers
        ]
    )

    const spacesState = useMemo(
        () => ({
            spaces,
            newSpaceName,
            setNewSpaceName,
            openAfterCreateTarget,
            setOpenAfterCreateTarget,
            spaceNameFeedback,
            canCreateSpace,
            tempSpaceTtlHours,
            isCreatingSpace
        }),
        [
            spaces,
            newSpaceName,
            setNewSpaceName,
            openAfterCreateTarget,
            setOpenAfterCreateTarget,
            spaceNameFeedback,
            canCreateSpace,
            tempSpaceTtlHours,
            isCreatingSpace
        ]
    )

    const handlers = useMemo(
        () => ({
            handleAddObject: guardEditAction(handleAddObject),
            handleSaveView,
            handleFrameAll,
            handleFrameSelection,
            handleUpdateTransformSnaps,
            handleSave,
            handleLoadClick,
            handleKeepCurrentWorld,
            handleClear: guardEditAction(handleClear),
            handleAssetFilesUpload: guardEditAction(handleAssetFilesUpload),
            handleUndo,
            handleRedo,
            selectObject,
            handleSelectObjectFromOutliner,
            handleToggleObjectVisibility: guardEditAction(handleToggleObjectVisibility),
            selectAllObjects,
            resetAxisLock,
            toggleAdminMode,
            requestManualMediaOptimization: guardEditAction(handleManualMediaOptimization),
            requestBatchMediaOptimization: guardEditAction(handleBatchMediaOptimization),
            copySelectedObject,
            pasteClipboardObject: guardEditAction(pasteClipboardObject),
            cutSelectedObject: guardEditAction(cutSelectedObject),
            duplicateSelectedObject: guardEditAction(duplicateSelectedObject),
            deleteSelectedObject: guardEditAction(deleteSelectedObject),
            handleUngroupSelection: guardEditAction(handleUngroupSelection),
            expandIdsWithGroups,
            handleCreateSelectionGroup: guardEditAction(handleCreateSelectionGroup),
            handleSelectSelectionGroup,
            handleDeleteSelectionGroup: guardEditAction(handleDeleteSelectionGroup),
            handleCreateNamedSpace,
            handleOpenSpace,
            handleCopySpaceLink,
            handleDeleteSpace,
            handleRenameSpace,
            handleToggleSpacePermanent,
            handleToggleSpaceEditLock,
            handleReloadFromServer,
            handlePublishToServer,
            socketEmit
        }),
        [
            handleAddObject,
            handleSaveView,
            handleFrameAll,
            handleFrameSelection,
            handleUpdateTransformSnaps,
            handleSave,
            handleLoadClick,
            handleKeepCurrentWorld,
            handleClear,
            handleAssetFilesUpload,
            handleUndo,
            handleRedo,
            selectObject,
            handleSelectObjectFromOutliner,
            handleToggleObjectVisibility,
            selectAllObjects,
            resetAxisLock,
            toggleAdminMode,
            handleManualMediaOptimization,
            handleBatchMediaOptimization,
            copySelectedObject,
            pasteClipboardObject,
            cutSelectedObject,
            duplicateSelectedObject,
            deleteSelectedObject,
            handleUngroupSelection,
            expandIdsWithGroups,
            handleCreateSelectionGroup,
            handleSelectSelectionGroup,
            handleDeleteSelectionGroup,
            handleCreateNamedSpace,
            handleOpenSpace,
            handleCopySpaceLink,
            handleDeleteSpace,
            handleRenameSpace,
            handleToggleSpacePermanent,
            handleToggleSpaceEditLock,
            handleReloadFromServer,
            handlePublishToServer,
            guardEditAction,
            socketEmit
        ]
    )

    const refs = useMemo(
        () => ({
            controlsRef,
            fileInputRef
        }),
        [controlsRef, fileInputRef]
    )

    const editorLayoutProps = useMemo(
        () => ({
            handleFileLoad,
            controlButtons: {
                sceneButtons,
                panelButtons,
                adminButtons,
                displayButtons,
                xrButtons,
                hiddenUiButtons
            },
            isLoading,
            isFileDragActive,
            mediaOptimizationPreference,
            setMediaOptimizationPreference,
            canCreateGroupSelection,
            xrStore,
            currentCameraSettings,
            cameraPosition,
            rendererRef,
            presentation,
            remoteCursorMarkers,
            handleCanvasPointerMove,
            handleCanvasPointerLeave
        }),
        [
            handleFileLoad,
            sceneButtons,
            panelButtons,
            adminButtons,
            displayButtons,
            xrButtons,
            hiddenUiButtons,
            isLoading,
            isFileDragActive,
            mediaOptimizationPreference,
            setMediaOptimizationPreference,
            canCreateGroupSelection,
            xrStore,
            currentCameraSettings,
            cameraPosition,
            rendererRef,
            presentation,
            remoteCursorMarkers,
            handleCanvasPointerMove,
            handleCanvasPointerLeave
        ]
    )

    return {
        sceneSettingsContext,
        syncState,
        spacesState,
        handlers,
        refs,
        editorLayoutProps
    }
}

export default useAppContextValues
